'use client';

import { GitCompare, Loader2, Minus, Trash2, ExternalLink, CheckCircle2, Download } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';

export default function ComparePage() {
  const [paperIds, setPaperIds] = useState<string[]>([]);
  const [isComparing, setIsComparing] = useState(false);
  const [comparison, setComparison] = useState<any>(null);
  const [error, setError] = useState<string | null>(null);
  const [selectedPaperDetails, setSelectedPaperDetails] = useState<any[]>([]);
  const [shouldAutoCompare, setShouldAutoCompare] = useState(false);

  useEffect(() => {
    const stored = sessionStorage.getItem('mrdu.comparePaperIds');
    if (stored) {
      try {
        const ids = JSON.parse(stored);
        if (Array.isArray(ids)) {
          setPaperIds(ids.slice(0, 5));
          setShouldAutoCompare(ids.length >= 2);
        }
        sessionStorage.removeItem('mrdu.comparePaperIds');
      } catch {
        sessionStorage.removeItem('mrdu.comparePaperIds');
      }
    const storedPapers = sessionStorage.getItem('mrdu.comparePapers');
    if (storedPapers) {
      try {
        const papers = JSON.parse(storedPapers);
        if (Array.isArray(papers)) setSelectedPaperDetails(papers.slice(0, 5));
      } catch {
        sessionStorage.removeItem('mrdu.comparePapers');
      }
      sessionStorage.removeItem('mrdu.comparePapers');
    }
    }
  }, []);

  const removePaper = (paperId: string) => {
    setPaperIds(paperIds.filter(id => id !== paperId));
  };

  const handleCompare = async () => {
    if (paperIds.length < 2) {
      setError('Please select at least 2 papers to compare');
      return;
    }
    setIsComparing(true);
    setError(null);
    try {
      const response = await fetch('/api/backend/research/comparison', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ paper_ids: paperIds }),
      });
      const data = await response.json();
      if (!response.ok) {
        throw new Error(data.detail || data.error || 'Comparison failed');
      }
      setComparison(data);
    } catch (e) {
      setError('Comparison failed');
    } finally {
      setIsComparing(false);
    }
  };

  useEffect(() => {
    if (!shouldAutoCompare || paperIds.length < 2) return;
    setShouldAutoCompare(false);
    void handleCompare();
  }, [paperIds, shouldAutoCompare]);

  const downloadComparisonReport = () => {
    if (!comparison?.papers?.length) return;
    const lines = [
      'Comparative Analysis Report',
      'Generated by MRDU Research Workspace',
      '',
      'Compared papers',
      ...comparison.papers.map((paper: any, index: number) =>
        `${index + 1}. ${paper.title || 'Untitled paper'} | ${paper.year || 'Year unavailable'} | ${paper.venue || 'Venue unavailable'}`
      ),
      '',
      ...comparison.rows.flatMap((row: any) => [
        row.feature,
        ...comparison.papers.map((paper: any, index: number) => {
          const value = row.values[paper.id];
          const text = typeof value === 'string' ? value : value?.text;
          return `Paper ${index + 1}: ${text || 'Not available'}`;
        }),
        '',
      ]),
    ];
    const blob = new Blob([createPdf(lines)], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = 'comparative-analysis-report.pdf';
    document.body.appendChild(anchor);
    anchor.click();
    anchor.remove();
    URL.revokeObjectURL(url);
  };

  const createPdf = (content: string[]) => {
    const sanitize = (value: string) => value
      .normalize('NFKD')
      .replace(/[^\x20-\x7E]/g, '')
      .replace(/[\\()]/g, (character) => `\\${character}`);
    const wrappedLines = content.flatMap((line) => {
      const words = sanitize(line).split(/\s+/).filter(Boolean);
      if (words.length === 0) return [''];
      const result: string[] = [];
      let current = '';
      words.forEach((word) => {
        const next = current ? `${current} ${word}` : word;
        if (next.length > 92 && current) {
          result.push(current);
          current = word;
        } else {
          current = next;
        }
      });
      if (current) result.push(current);
      return result;
    });
    const linesPerPage = 48;
    const pages = Array.from(
      { length: Math.max(1, Math.ceil(wrappedLines.length / linesPerPage)) },
      (_, index) => wrappedLines.slice(index * linesPerPage, (index + 1) * linesPerPage)
    );
    const objects: string[] = [
      '<< /Type /Catalog /Pages 2 0 R >>',
      `<< /Type /Pages /Kids [${pages.map((_, index) => `${5 + index * 2} 0 R`).join(' ')}] /Count ${pages.length} >>`,
      '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
      '<< /Length 0 >>\nstream\n\nendstream',
    ];
    pages.forEach((pageLines, pageIndex) => {
      const stream = ['BT', '/F1 11 Tf', '50 750 Td',
        ...pageLines.flatMap((line, lineIndex) => [
          `(${sanitize(line)}) Tj`,
          ...(lineIndex < pageLines.length - 1 ? ['0 -15 Td'] : []),
        ]), 'ET'].join('\n');
      objects.push(
        `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents ${6 + pageIndex * 2} 0 R >>`,
        `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`
      );
    });
    let pdf = '%PDF-1.4\n';
    const offsets = [0];
    objects.forEach((object, index) => {
      offsets[index + 1] = pdf.length;
      pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
    });
    const xrefOffset = pdf.length;
    pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
    offsets.slice(1).forEach((offset) => { pdf += `${String(offset).padStart(10, '0')} 00000 n \n`; });
    return `${pdf}trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      <div>
        <div className="flex items-start justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Comparative Analysis</h1>
            <p className="text-gray-600 dark:text-gray-400 mt-1">
              Compare research questions, methods, datasets, experiments, and evaluation metrics side by side.
            </p>
          </div>
          {paperIds.length > 0 && (
            <Button variant="outline" onClick={() => { setPaperIds([]); setComparison(null); sessionStorage.removeItem('mrdu.comparePaperIds'); }}>
              <Trash2 className="w-4 h-4 mr-2" /> Clear selection
            </Button>
          )}
        </div>
      </div>

      {/* Selected Papers */}
      {paperIds.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Selected Papers ({paperIds.length}/5)</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">
              {paperIds.map((id, index) => {
                const paper = selectedPaperDetails.find((item) => (item.external_id || item.id) === id);
                return (
                  <div key={id} className="rounded-lg border border-primary/20 bg-primary/5 p-4">
                    <div className="flex items-start justify-between gap-2">
                      <Badge variant="secondary">Paper {index + 1}</Badge>
                      <button onClick={() => removePaper(id)} className="text-gray-400 hover:text-red-500" aria-label={`Remove paper ${index + 1}`}>
                        <Minus className="w-4 h-4" />
                      </button>
                    </div>
                    <p className="font-medium mt-3 line-clamp-3">{paper?.title || id}</p>
                    <p className="text-xs text-gray-500 mt-2">{paper?.year || 'Year unavailable'} · {paper?.venue || 'Source unavailable'}</p>
                  </div>
                );
              })}
            </div>
            {paperIds.length >= 2 && (
              <Button
                onClick={handleCompare}
                disabled={isComparing}
                className="mt-4 w-full"
                size="lg"
              >
                {isComparing ? <><Loader2 className="w-4 h-4 mr-2 animate-spin" /> Comparing papers...</> : <><GitCompare className="w-4 h-4 mr-2" /> Compare {paperIds.length} papers</>}
              </Button>
            )}
          </CardContent>
        </Card>
      )}

      {error && (
        <div className="p-4 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg text-red-600 dark:text-red-400">
          {error}
        </div>
      )}

      {/* Comparison Results */}
      {comparison && (
        <div className="space-y-4">
          <div className="flex items-center justify-between gap-2">
            <CheckCircle2 className="w-5 h-5 text-green-600" />
            <h2 className="text-xl font-semibold">Comparison results</h2>
            <Button variant="outline" size="sm" onClick={downloadComparisonReport}>
              <Download className="w-4 h-4 mr-2" /> Download PDF report
            </Button>
          </div>
          {comparison.error && <div className="p-4 bg-amber-50 border border-amber-200 rounded-lg text-amber-700">{comparison.error}</div>}
          <div className="grid gap-4 md:grid-cols-2">
            {comparison.papers.map((paper: any, index: number) => (
              <Card key={paper.id}>
                <CardHeader>
                  <CardTitle className="text-base">Paper {index + 1}</CardTitle>
                </CardHeader>
                <CardContent>
                  <h3 className="font-semibold">{paper.title}</h3>
                  <p className="text-sm text-gray-500 mt-1">{paper.year || 'Year unavailable'} · {paper.venue || 'Venue unavailable'}</p>
                  {paper.url && <a href={paper.url} target="_blank" rel="noreferrer" className="inline-flex items-center text-sm text-primary mt-3 hover:underline">Open paper <ExternalLink className="w-3 h-3 ml-1" /></a>}
                </CardContent>
              </Card>
            ))}
          </div>
          <div className="space-y-4">
            {comparison.rows.map((row: any) => (
              <Card key={row.feature}>
                <CardHeader><CardTitle className="text-base">{row.feature}</CardTitle></CardHeader>
                <CardContent className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                  {comparison.papers.map((paper: any, index: number) => {
                    const value = row.values[paper.id];
                    const text = typeof value === 'string' ? value : value?.text;
                    return (
                      <div key={paper.id} className="border-l-2 border-primary/30 pl-3">
                        <p className="text-xs font-semibold text-gray-500 mb-1">Paper {index + 1}</p>
                        <p className="text-sm whitespace-pre-wrap">{text || 'Not available'}</p>
                      </div>
                    );
                  })}
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}